technical:
  - "C# Basic"
  - "C# Intermediate"
  - "C# Advanced"
  - "DBs relational"
  - "DBs no sql"
  - "Security"
  - "Cloud"
  - "Personal projects"
  - "Last work project"
  - "DevOps"
  - "Web development"
  - "Web SPA - Angular"

non_technical:
  - "Potential & Motivation a.k.a Drive"
  - "Communication"
  - "Self impression"

personal_assessment:
  - "Overall impression"
  - "Cultural fit"
  - "Growth potential"

overall_levels:
  - "Junior"
  - "Medior"
  - "Senior"
  - "Lead"
